export const LOGIN_USER = 'LOGIN_USER';

export const OPEN_LOGIN_POPUP = 'OPEN_LOGIN_POPUP';
export const CLOSE_LOGIN_POPUP = 'CLOSE_LOGIN_POPUP';
export const LOADING_LOGIN_POPUP = 'LOADING_LOGIN_POPUP';
export const LOADED_LOGIN_POPUP = 'LOADED_LOGIN_POPUP';
export const SET_ERROR_LOGIN_POPUP = 'SET_ERROR_LOGIN_POPUP';
export const CLEAR_ERROR_LOGIN_POPUP = 'CLEAR_ERROR_LOGIN_POPUP';

export const ADD_ENVELOPE_ID = 'ADD_ENVELOPE_ID';
export const ENVELOPES_LOADED = 'ENVELOPES_LOADED';

export const TEMPLATES_LOADED = 'TEMPLATES_LOADED';

export const ADD_CONTACT = 'CREATE_CONTACT';
export const EDIT_CONTACT = 'EDIT_CONTACT';

export const CLEAR_STATE = 'CLEAR_STATE';
